# Schema for the configuration files of the Spotify Integration module.
spotify_integration.settings:
  type: config_object
  label: 'Spotify Integration settings'
  mapping:
    spotify_url:
      type: url
      label: 'Spotify URL'
